In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dirty_cafe_sales (1).csv')

In [3]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [5]:
# removing spacing from columns

df.columns = df.columns.str.replace(' ', '_')

In [6]:
#check % of missing data

df.isna().mean() * 100

Transaction_ID       0.00
Item                 3.33
Quantity             1.38
Price_Per_Unit       1.79
Total_Spent          1.73
Payment_Method      25.79
Location            32.65
Transaction_Date     1.59
dtype: float64

Item colums
. improper casing = proper casing
. error - Unknown
. missing spaces - Unknown

In [7]:
#view the records where items are missing

df[df['Item'].isna()]

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
30,TXN_1736287,NaN,5,2.0,10.0,Digital Wallet,NaN,2023-06-02
61,TXN_8051289,NaN,1,3.0,3.0,NaN,In-store,2023-10-09
72,TXN_6044979,NaN,1,1.0,1.0,Cash,In-store,2023-12-08
89,TXN_4132730,NaN,5,1.0,5.0,NaN,In-store,2023-03-12
...,...,...,...,...,...,...,...,...
9820,TXN_8751702,NaN,5,NaN,15.0,Cash,NaN,2023-02-13
9855,TXN_3740505,NaN,2,1.5,3.0,NaN,NaN,2023-11-21
9876,TXN_3105633,NaN,1,2.0,2.0,NaN,In-store,2023-03-30
9885,TXN_4659954,NaN,3,4.0,12.0,Credit Card,In-store,NaN
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02

In [8]:
#filling the missing data in items with Unknown, correcting casing and Error

df['Item'] = df['Item'].str.strip().str.title().fillna('Unknown').replace('Error', 'Unknown')

In [9]:
df.head(10)

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,Unknown,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,Unknown,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

Quantity column
.Missing values
.Error
. Wrong datatype

The 3 columsn (quantity, price per unit and total spent). We need at least two of them to fill the next. 
If 2 of these columns are missing, I cannot work with them so i will drop them

In [10]:
# Fields where both Quantity and price per unit is missing

df[df['Quantity'].isna() & df['Price_Per_Unit'].isna()]

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
912,TXN_1575608,Sandwich,NaN,NaN,20.0,ERROR,Takeaway,2023-01-05

In [11]:
# Fields where both Quantity and  Tototal amount is missing

df[df['Quantity'].isna() & df['Total_Spent'].isna()]

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
3401,TXN_3251829,Tea,NaN,1.5,NaN,Digital Wallet,In-store,2023-07-25
8479,TXN_1547245,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-09-11
8732,TXN_4550558,Cookie,NaN,1.0,NaN,Credit Card,In-store,2023-08-04

In [12]:
#Dropping them
df = df.dropna(subset =['Quantity','Price_Per_Unit'], how ='all' )

In [13]:
df =df.dropna(subset = ['Quantity', 'Total_Spent'], how = 'all')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9996 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    9996 non-null   object
 1   Item              9996 non-null   object
 2   Quantity          9862 non-null   object
 3   Price_Per_Unit    9818 non-null   object
 4   Total_Spent       9826 non-null   object
 5   Payment_Method    7418 non-null   object
 6   Location          6731 non-null   object
 7   Transaction_Date  9837 non-null   object
dtypes: object(8)
memory usage: 702.8+ KB

In [15]:
df[df['Quantity'] =='ERROR']

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
20,TXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04
55,TXN_5522862,Cookie,ERROR,1.0,2.0,Credit Card,Takeaway,2023-03-19
117,TXN_2148617,Juice,ERROR,3.0,9.0,Digital Wallet,UNKNOWN,2023-01-10
177,TXN_1896955,Salad,ERROR,5.0,25.0,NaN,In-store,2023-09-23
178,TXN_5075974,Smoothie,ERROR,4.0,16.0,Digital Wallet,NaN,2023-04-11
...,...,...,...,...,...,...,...,...
9832,TXN_3325234,Tea,ERROR,1.5,1.5,ERROR,In-store,2023-08-26
9846,TXN_7621213,Coffee,ERROR,2.0,6.0,NaN,In-store,2023-03-07
9911,TXN_2464054,Coffee,ERROR,2.0,10.0,NaN,Takeaway,2023-08-18
9935,TXN_9778251,Tea,ERROR,1.5,6.0,NaN,Takeaway,2023-11-09
9957,TXN_6487003,Coffee,ERROR,2.0,8.0,Credit Card,Takeaway,2023-11-15

In [16]:
# Replacing ERRORS and missing values with 0

df['Quantity'] = df['Quantity'].replace('ERROR',0).fillna(0)

df['Price_Per_Unit']=df['Price_Per_Unit'].replace('ERROR',0).fillna(0)

df['Total_Spent'] =df['Total_Spent'].replace('ERROR',0).fillna(0)

In [17]:
df.tail(20)

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
9980,TXN_6796890,Tea,4,1.5,6.0,UNKNOWN,NaN,2023-08-24
9981,TXN_4583012,Unknown,5,4.0,20.0,Digital Wallet,NaN,2023-02-27
9982,TXN_8567525,Cookie,2,1.0,2.0,NaN,Takeaway,2023-12-30
9983,TXN_9226047,Smoothie,3,4.0,12.0,Cash,NaN,UNKNOWN
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9985,TXN_3297457,Cake,2,3.0,6.0,NaN,UNKNOWN,2023-01-03
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9987,TXN_1784478,Juice,5,3.0,15.0,Cash,NaN,2023-07-31
9988,TXN_9594133,Cake,5,3.0,0,ERROR,NaN,NaN
9989,TXN_1741685,Juice,5,3.0,15.0,Cash,NaN,2023-08-18
9990,TXN_1538510,Coffee,5,2.0,10.0,Digital Wallet,NaN,2023-05-22
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9993,TXN_4766549,Smoothie,2,4.0,0,Cash,NaN,2023-10-20
9994,TXN_7851634,Unknown,4,4.0,16.0,NaN,NaN,2023-01-08
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,Unknown,3,0,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,0,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

### Chaning numeric columns datatype and calculations

In [18]:
#Changed all numeric columns from string to numeric datatye

df['Quantity']= pd.to_numeric(df['Quantity'], errors = 'coerce')

df['Price_Per_Unit']= pd.to_numeric(df['Price_Per_Unit'], errors = 'coerce')

df['Total_Spent']= pd.to_numeric(df['Total_Spent'], errors = 'coerce')

In [19]:
# Calculating missing numeric columns

df['Quantity'] = np.where(df['Quantity'] == 0.0, df['Total_Spent'] / df['Price_Per_Unit'], df['Quantity'])

df['Price_Per_Unit'] = np.where(df['Price_Per_Unit'] == 0.0, df['Total_Spent'] / df['Quantity'], df['Price_Per_Unit'])

df['Total_Spent'] = np.where(df['Total_Spent'] == 0.0, df['Quantity'] * df['Price_Per_Unit'], df['Total_Spent'])

In [20]:
#Checking the distinct items in the column

df['Payment_Method'].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan],
      dtype=object)

ISSUES WITH PAYMENT METHOD COLUMN
we have ERROR, nan, inconsistent casing

In [21]:
#fixing the payment method issues

df['Payment_Method'] = df['Payment_Method'].str.title().str.replace('ERROR','Unknown').fillna('Unknown').str.strip()

In [22]:
#Checking the distinct items in the location column

df['Location'].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR'], dtype=object)

In [23]:
#fixing issues in the location column

df['Location'] = df['Location'].str.title().str.replace('ERROR','Unknown').fillna('Unknown').str.strip()

In [24]:
#Viewing the null dates

df[df['Transaction_Date'].isnull()]

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
77,TXN_2091733,Salad,1.0,5.0,5.0,Unknown,In-Store,NaN
104,TXN_7447872,Juice,2.0,3.0,6.0,Unknown,Unknown,NaN
160,TXN_1093800,Sandwich,3.0,4.0,12.0,Cash,Takeaway,NaN
175,TXN_6463132,Cookie,5.0,1.0,5.0,Credit Card,Takeaway,NaN
246,TXN_1908636,Tea,2.0,1.5,3.0,Unknown,Unknown,NaN
...,...,...,...,...,...,...,...,...
9769,TXN_9686177,Cake,3.0,3.0,9.0,Unknown,In-Store,NaN
9833,TXN_5536245,Smoothie,4.0,4.0,16.0,Cash,Unknown,NaN
9885,TXN_4659954,Unknown,3.0,4.0,12.0,Credit Card,In-Store,NaN
9931,TXN_8344810,Smoothie,2.0,4.0,8.0,Unknown,Unknown,NaN
9988,TXN_9594133,Cake,5.0,3.0,15.0,Error,Unknown,NaN

In [25]:
#filling empty dates with unknown

df['Transaction_Date'] = df['Transaction_Date'].fillna('Unknown').str.replace('ERROR','Unknown')

In [26]:
df.head(20)

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-Store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-Store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Unknown,Unknown,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-Store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,Unknown,2023-03-31
6,TXN_4433211,Unknown,3.0,3.0,9.0,Error,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,Unknown,2023-10-28
8,TXN_4717867,Unknown,5.0,3.0,15.0,Unknown,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,Unknown,In-Store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,Unknown
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-Store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,Unknown,Takeaway,2023-06-01
14,TXN_8915701,Unknown,2.0,1.5,3.0,Unknown,In-Store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-Store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,Unknown,Unknown,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-Store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,Error,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15

In [27]:
# df.to_csv(r'C:\\Users\\lenovo\Downloads\Coffee_clean.csv', index = False)

In [28]:
df

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-Store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-Store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Unknown,Unknown,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-Store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Unknown,Unknown,2023-08-30
9996,TXN_9659401,Unknown,3.0,1.0,3.0,Digital Wallet,Unknown,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Unknown,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,Unknown,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-Store,2023-11-07